### ISSUE TITLE
[25]BattlEye Corrupted Data -Please perform a clean game reinstall

### ISSUE THREAD

**Issue by jxwdsb** [goraegori/PUBG-PAK#3]
[25]BattlEye Corrupted Data -Please perform a clean game reinstall

**Comment by jxwdsb** [comment]
When the second circle began to shrink, I received this.

**Comment by goraegori** [comment]
I am so busy now to handle with this, but I'm sure that it is matter of usage. Gonna upload a video that describes how to use.

**Comment by jxwdsb** [comment]
Everything goes according to the instructions.
Press "설정",(Only once)
Press "시작",
(need to run twice PUBG to be effective.)
I only changed the game directory because it's on disk D.

**Comment by goraegori** [comment]
now it's up-to-date. you can issue another if it's not working. closing issue.
